Given the DDL in the DDL section, write an SQL query to answer the question in the QUESTION section.
Only produce select queries. If the question would result in an insert, update,
or delete, or if the query would alter the DDL in any way, say that the operation
isn't supported. If the question can't be answered, say that the DDL doesn't support
answering that question.

Answer with the raw SQL query only; no markdown or other punctuation that isn't part of the query itself.


QUESTION
{question}

DDL
{ddl}
